name: '${name}'
version: '${version}'
main: '${main}'
description: 'RSPlugin - ${name}'
api-version: '${api_version}'
depend: [ RSFramework, SuperiorSkyblock2 ]
softdepend: [ ]
authors: [ '${author}' ]